"""
Configuracion y datos para el generador de mapas conceptuales.
Edita este archivo para cambiar el contenido (concept_map) y los parametros de dibujo.
"""
import os
import sys

NORMALIZAR_TUPLAS = True
PALABRAS_POR_POSICION = 2

concept_map = [
    {
        "titulo_principal": "Unidad 4. Aplicaciones con técnicas de IA",
        "subtitulos": [
            {
                "titulo": "4.1. Robótica",
                "conector": "Incluye el área de",
                "ramas": [
                    {
                        "titulo": "4.1.1. Conceptos básicos.",
                        "conector": "contiene",
                        "ramas": [[
                            # RAMA 1: Definición y Componentes Clave (Originalmente expandida)
                            (None, "Se define como la"),
                            ("Robótica", "Ciencia y"),
                            ("Tecnología", "de los"),
                            ("Robots", "que son"),
                            ("Máquinas programables", "capaces de"),
                            ("Realizar tareas", "en el"),
                            ("Mundo físico", "con"),
                            ("Autonomía variable", "y que poseen"),
                            ("Actuadores", "para"),
                            ("Movimiento", "y"),
                            ("Sensores", "para"),
                            ("Percepción", "con"),
                            ("Controladores", "que"),
                            ("Procesan información", "y toman"),
                            ("Decisiones", "basado en"),
                            ("Algoritmos", "que rigen"),
                            ("Su comportamiento", "y que interactúan con"),
                            ("Su entorno", "a través de"),
                            ("Interfaces", "para"),
                            ("Comunicación", "lo que los hace"),
                            ("Sistemas mecatrónicos", "que integran"),
                            ("Mecánica, electrónica e informática", "para lograr"),
                            ("Objetivos específicos", "como"),
                            ("Manipulación", "de"),
                            ("Objetos", "o"),
                            ("Navegación", "en"),
                            ("Espacios complejos", "su estructura se compone de"),
                            ("Efectores finales", "para"),
                            ("Interacción directa", "e implican"),
                            ("Cinemática", "que estudia el"),
                            ("Movimiento", "sin considerar"),
                            ("Fuerzas", "y"),
                            ("Dinámica", "que incluye las"),
                            ("Fuerzas y torques", "además de requerir"),
                            ("Programación", "en"),
                            ("Lenguajes especializados", "y cumplen con"),
                            ("Grados de libertad", "que son el número de"),
                            ("Articulaciones independientes", None)
                        ],
                        [
                            # RAMA 2: Ciclo de Control y Sistemas de Coordenadas (Nueva rama)
                            (None, "La funcionalidad de un robot se basa en el"),
                            ("Ciclo de control", "que involucra"),
                            ("Percepción", "mediante"),
                            ("Sensores internos y externos", "para obtener"),
                            ("Datos del entorno", "luego se realiza"),
                            ("Procesamiento", "en la"),
                            ("Unidad de control (Controlador)", "para"),
                            ("Tomar decisiones", "basadas en el"),
                            ("Programa de tareas", "y generar"),
                            ("Señales de salida", "hacia los"),
                            ("Actuadores", "que convierten"),
                            ("Energía", "en"),
                            ("Movimiento físico", "la interfaz con el mundo es el"),
                            ("Efector final (End-Effector)", "que puede ser un"),
                            ("Gripper (pinza)", "o una"),
                            ("Herramienta especializada", "la fuente de"),
                            ("Potencia", "puede ser"),
                            ("Eléctrica", "o"),
                            ("Hidráulica/Neumática", "y la posición se define en un"),
                            ("Espacio de trabajo", "o"),
                            ("Envolvente de trabajo", "usando"),
                            ("Sistemas de coordenadas", "que pueden ser"),
                            ("Mundo, Base, Herramienta", "o"),
                            ("Articulación", "que es un"),
                            ("Eje de movimiento", None)
                        ]
                        ],
                    },
                    {
                        "titulo": "4.1.2. Clasificación.",
                        "conector": "Se clasifican según",
                        "ramas": [[
                            # RAMA 1: Estructura, Aplicación y Movilidad (Originalmente expandida)
                            (None, "Se clasifican por"),
                            ("Estructura", "en"),
                            ("Cartesianos", "o"),
                            ("Rectangulares", "que usan"),
                            ("Coordenadas x,y,z", "y por"),
                            ("Cilíndricos", "con"),
                            ("Rotación en base", "y"),
                            ("Esféricos", "o"),
                            ("Polares", "que usan"),
                            ("Ángulos y radio", "además de"),
                            ("Articulados", "o"),
                            ("Antropomórficos", "similares al"),
                            ("Brazo humano", "también por"),
                            ("Aplicación", "en"),
                            ("Industriales", "para"),
                            ("Manufactura", "o"),
                            ("De servicio", "para"),
                            ("Tareas domésticas o médicas", "y por"),
                            ("Movilidad", "en"),
                            ("Fijos", "o"),
                            ("Móviles", "estos últimos incluyen"),
                            ("Vehículos terrestres, aéreos", "y"),
                            ("Subacuáticos", "otras clasificaciones son por"),
                            ("Método de control", "en"),
                            ("Punto a punto", "o"),
                            ("Trayectoria continua", "y por"),
                            ("Generación", "en"),
                            ("Primera generación", "que son"),
                            ("Manipuladores simples", "y"),
                            ("Segunda generación", "con"),
                            ("Sensores limitados", "además de"),
                            ("Tercera generación", "con"),
                            ("IA y percepción avanzada", "e incluso"),
                            ("Cuarta generación", "enfocada en"),
                            ("Sistemas autónomos", "y por"),
                            ("Mecanismo de accionamiento", "en"),
                            ("Hidráulicos", "o"),
                            ("Neumáticos", "y"),
                            ("Eléctricos", None)
                        ],
                        [
                            # RAMA 2: Nivel de Control, Energía y Precisión (Nueva rama)
                            (None, "Una clasificación adicional es por"),
                            ("Nivel de control", "en"),
                            ("Robots no servo-controlados", "que solo tienen"),
                            ("Movimiento de inicio/parada", "y"),
                            ("Robots servo-controlados", "que permiten"),
                            ("Control de posición y velocidad", "también se clasifican por"),
                            ("Tipo de energía", "en"),
                            ("Eléctricos", "que son los más"),
                            ("Comunes", "y"),
                            ("Neumáticos", "para"),
                            ("Aplicaciones de alta velocidad", "o"),
                            ("Hidráulicos", "para"),
                            ("Fuerza elevada", "además por"),
                            ("Precisión", "en"),
                            ("Repetibilidad", "que es la capacidad de"),
                            ("Volver al mismo punto", "y"),
                            ("Exactitud", "que es la proximidad al"),
                            ("Punto deseado", "se dividen por"),
                            ("Entorno de operación", "en"),
                            ("Industrial", "o"),
                            ("Doméstico/Consumo", "e incluso"),
                            ("Exploración (espacial o submarina)", "y por"),
                            ("Grado de autonomía", "en"),
                            ("Supervisados", "o"),
                            ("Totalmente autónomos", None)
                        ]
                        ],
                    },
                    {
                        "titulo": "4.1.3. Desarrollos actuales y aplicaciones.",
                        "conector": "Incluyen",
                        "ramas": [[
                            # RAMA 1: Cobots, Robótica Blanda y Aplicaciones Clásicas (Originalmente expandida)
                            (None, "Los desarrollos incluyen"),
                            ("Robots colaborativos (Cobots)", "que"),
                            ("Trabajan junto a humanos", "y"),
                            ("Robótica blanda", "con"),
                            ("Materiales flexibles", "para"),
                            ("Interacciones seguras", "además de"),
                            ("Sistemas autónomos", "para"),
                            ("Exploración espacial o subacuática", "y"),
                            ("Drones inteligentes", "para"),
                            ("Vigilancia o entrega", "y"),
                            ("Nanobots", "para"),
                            ("Medicina (nanomedicina)", "con aplicaciones en"),
                            ("Cirugía robótica", "para"),
                            ("Procedimientos de alta precisión", "y en"),
                            ("Almacenes automatizados", "para"),
                            ("Logística avanzada", "así como en"),
                            ("Agricultura de precisión", "para"),
                            ("Monitorización y cosecha", "y en"),
                            ("Asistencia a personas mayores", "como"),
                            ("Robots de compañía", "y en"),
                            ("Educación", "como"),
                            ("Herramientas didácticas", "otros avances son en"),
                            ("Biónica y prótesis robóticas", "para"),
                            ("Reemplazo de extremidades", "y en"),
                            ("Robots humanoides", "para"),
                            ("Interacción social compleja", "y"),
                            ("Robótica móvil avanzada", "para"),
                            ("Navegación en entornos dinámicos", "e incluyen"),
                            ("Vehículos guiados automáticamente (AGV)", "para"),
                            ("Transporte de materiales", "y"),
                            ("Inspección de infraestructuras", "usando"),
                            ("Sensores no destructivos", "también en"),
                            ("Manufactura aditiva (Impresión 3D)", "con"),
                            ("Brazo robótico", None)
                        ],
                        [
                            # RAMA 2: Bioinspirada, Enjambre, HRI y Ética (Nueva rama)
                            (None, "Otros desarrollos se enfocan en"),
                            ("Robótica bioinspirada", "que imita la"),
                            ("Naturaleza y biología", "para lograr"),
                            ("Movimiento eficiente", "como"),
                            ("Robots andadores o nadadores", "y en"),
                            ("Robótica de enjambre (Swarm Robotics)", "donde"),
                            ("Múltiples robots simples", "cooperan para"),
                            ("Tareas complejas", "además de"),
                            ("Interacción Humano-Robot (HRI)", "para mejorar la"),
                            ("Colaboración y comunicación", "entre"),
                            ("Personas y máquinas", "lo que implica"),
                            ("Ética robótica", "y consideraciones de"),
                            ("Seguridad y privacidad", "y se aplican en"),
                            ("Medicina personalizada", "con"),
                            ("Microrobots", "para"),
                            ("Entrega dirigida de fármacos", "y en"),
                            ("Construcción", "para"),
                            ("Tareas peligrosas o repetitivas", "así como en"),
                            ("Búsqueda y rescate", "en"),
                            ("Zonas de desastre", "y en"),
                            ("Entretenimiento", "con"),
                            ("Robots de interacción social", "para"),
                            ("Experiencias inmersivas", "e incluso en"),
                            ("Desmantelamiento nuclear", "por"),
                            ("Condiciones extremas", None)
                        ]
                        ],
                    },
                ],
            },
            {
                "titulo": "4.2. Redes Neuronales (RN)",
                "conector": "Utiliza modelos de",
                "ramas": [
                    {
                        "titulo": "4.2.1. Conceptos básicos",
                        "conector": "que son un",
                        "ramas": [[
                            (None,"Son un"),
                             ("Modelo computacional","inspirado en el"),
                             ("Cerebro biológico","y se componen de"),
                             ("Neuronas artificiales (nodos)","que están"),
                             ("Conectadas","mediante"),
                             ("Pesos (weights)","que modulan la"),
                             ("Señal de entrada","que es"),
                             ("Sumada","y pasa por una"),
                             ("Función de activación","para producir una"),
                             ("Salida","se organizan en"),
                             ("Capas (layers)","como la"),
                             ("Capa de entrada (input)","la"),
                             ("Capa oculta (hidden)","y la"),
                             ("Capa de salida (output)","y aprenden por"),
                             ("Entrenamiento","ajustando los"),
                             ("Pesos","mediante"),
                             ("Algoritmos de optimización","como"),
                             ("Retropropagación (Backpropagation)","para"),
                             ("Minimizar errores","en la"),
                             ("Función de pérdida (Loss Function)", None)
                        ],
                        [
                            # RAMA 2: Proceso de Aprendizaje y Componentes (Nueva rama)
                            (None, "El aprendizaje se logra con un"),
                            ("Conjunto de datos (Dataset)", "dividido en"),
                            ("Entrenamiento, Validación y Prueba", "para"),
                            ("Ajustar y evaluar el modelo", "el proceso inicia con la"),
                            ("Inicialización de pesos", "de forma"),
                            ("Aleatoria o predefinida", "luego, para cada"),
                            ("Lote (Batch) de datos", "se calcula la"),
                            ("Salida predicha (Forward Pass)", "y se compara con la"),
                            ("Salida real", "usando una"),
                            ("Métrica de error (Loss)", "el error se propaga hacia atrás con"),
                            ("Backpropagation", "para calcular el"),
                            ("Gradiente de la función de pérdida", "que indica la"),
                            ("Dirección de máximo error", "luego, un"),
                            ("Optimizador (e.g., Adam, SGD)", "actualiza los"),
                            ("Pesos", "en dirección"),
                            ("Opuesta al gradiente", "usando una"),
                            ("Tasa de aprendizaje (Learning Rate)", "que es un"),
                            ("Hiperparámetro clave", "este ciclo se repite por varias"),
                            ("Épocas (Epochs)", "hasta que el modelo"),
                            ("Converge", "evitando el"),
                            ("Sobreajuste (Overfitting)", "donde el modelo"),
                            ("Memoriza los datos de entrenamiento", "o el"),
                            ("Subajuste (Underfitting)", "donde"),
                            ("No aprende patrones", None)
                        ]],
                    },
                    {
                        "titulo": "4.2.2. Clasificación",
                        "conector": "que se clasifican por",
                        "ramas": [[
                            (None,"Se clasifican por"),
                             ("Arquitectura","en"),
                             ("Redes feedforward","donde la información"),
                             ("Fluye en una dirección","y"),
                             ("Redes recurrentes (RNN)","que tienen"),
                             ("Conexiones de retroalimentación","para"),
                             ("Procesar secuencias","también por"),
                             ("Tipo de aprendizaje","en"),
                             ("Supervisado","con"),
                             ("Datos etiquetados","y"),
                             ("No supervisado","para"),
                             ("Descubrir patrones","o"),
                             ("Por refuerzo","para"),
                             ("Aprender por interacciones","e incluyen"),
                             ("Redes Convolucionales (CNN)","para"),
                             ("Imágenes","y"),
                             ("Transformers","para"),
                             ("Secuencias de texto","así como"),
                             ("Redes Generativas Antagónicas (GAN)","para"),
                             ("Generación de datos", None)
                        ],
                        [
                            # RAMA 2: Tipos de Capas y Funciones de Activación (Nueva rama)
                            (None, "También se clasifican por el"),
                            ("Tipo de capas", "que pueden ser"),
                            ("Capas densas (Fully Connected)", "donde cada"),
                            ("Neurona se conecta con todas las de la capa anterior", "o"),
                            ("Capas convolucionales", "que aplican"),
                            ("Filtros para extraer características locales", "o"),
                            ("Capas de pooling", "para"),
                            ("Reducir la dimensionalidad espacial", "además por su"),
                            ("Función de activación", "que introduce"),
                            ("No linealidad", "y puede ser"),
                            ("Sigmoide o Tangente Hiperbólica", "que saturan y pueden causar"),
                            ("Problema del gradiente evanescente", "o la función"),
                            ("ReLU (Rectified Linear Unit)", "que es"),
                            ("Lineal para valores positivos", "y previene la saturación, o sus variantes como"),
                            ("Leaky ReLU y ELU", "para manejar"),
                            ("Neuronas muertas", "también existen"),
                            ("Mapas autoorganizados (SOM)", "para"),
                            ("Visualización y clustering", "y"),
                            ("Redes de base radial (RBF)", "que usan"),
                            ("Funciones de base radial", "y arquitecturas como"),
                            ("Autoencoders", "para"),
                            ("Reducción de dimensionalidad no lineal", "o"),
                            ("U-Nets", "para"),
                            ("Segmentación de imágenes biomédicas", None)
                        ]],
                    },
                    {
                        "titulo": "4.2.3. Desarrollos actuales y aplicaciones",
                        "conector": "que incluyen",
                        "ramas": [[
                            (None,"Los desarrollos incluyen"),
                             ("Deep Learning","que usa"),
                             ("Múltiples capas ocultas","para"),
                             ("Aprender jerarquías de características","y"),
                             ("Modelos de lenguaje grandes (LLM)","para"),
                             ("Generación de texto y diálogo","con aplicaciones en"),
                             ("Reconocimiento de voz","para"),
                             ("Asistentes virtuales","y en"),
                             ("Visión por computadora","para"),
                             ("Detección de objetos","y"),
                             ("Clasificación de imágenes","además de en"),
                             ("Sistemas de recomendación","para"),
                             ("Personalización de contenido","y en"),
                             ("Traducción automática","para"),
                             ("Comunicación global","e incluso en"),
                             ("Diagnóstico médico","para"),
                             ("Análisis de imágenes médicas", None)
                        ],
                        [
                            # RAMA 2: Fronteras de la Investigación y Aplicaciones Emergentes (Nueva rama)
                            (None, "Las fronteras de la investigación incluyen"),
                            ("Redes Neuronales Físicamente Informadas (PINN)", "que incorporan"),
                            ("Leyes físicas como restricciones", "en el entrenamiento, y las"),
                            ("Redes Neuronales Gráficas (GNN)", "para modelar"),
                            ("Datos en estructuras de grafos", "como"),
                            ("Redes sociales o moléculas", "también el"),
                            ("Aprendizaje por Transferencia (Transfer Learning)", "donde un modelo"),
                            ("Pre-entrenado se adapta a una nueva tarea", "ahorrando"),
                            ("Cómputo y datos", "y el"),
                            ("Aprendizaje Federado", "para entrenar modelos"),
                            ("En datos descentralizados", "sin comprometer la"),
                            ("Privacidad", "con aplicaciones en"),
                            ("Descubrimiento de fármacos", "para predecir"),
                            ("Interacciones moleculares", "y en"),
                            ("Ciencias del clima", "para"),
                            ("Modelar y predecir patrones climáticos", "además de en"),
                            ("Finanzas cuantitativas", "para"),
                            ("Predicción de mercados y gestión de riesgos", "y la"),
                            ("Generación de arte y música", "usando"),
                            ("Modelos generativos avanzados", "así como en"),
                            ("Conducción autónoma", "para la"),
                            ("Fusión de sensores", "y la"),
                            ("Toma de decisiones en tiempo real", None)
                        ]],
                    },
                ],
            },
            {
                "titulo": "4.3. Visión artificial",
                "conector": "Se relaciona con la",
                "ramas": [
                    {
                        "titulo": "4.3.1. Conceptos básicos",
                        "conector": "que es un",
                        "ramas": [[
                            (None,"Es un"),
                             ("Campo de la IA","que permite a las"),
                             ("Computadoras","obtener"),
                             ("Información de imágenes o videos","e incluye"),
                             ("Adquisición de imágenes","mediante"),
                             ("Cámaras o sensores","y"),
                             ("Preprocesamiento","para"),
                             ("Mejorar la calidad","como"),
                             ("Normalización o filtrado","seguido por"),
                             ("Segmentación","para"),
                             ("Dividir la imagen en partes","y"),
                             ("Extracción de características","para"),
                             ("Identificar bordes, formas o texturas","y"),
                             ("Reconocimiento","para"),
                             ("Asignar etiquetas o clases","usando"),
                             ("Algoritmos de Machine Learning","como"),
                             ("CNNs","que aprenden"),
                             ("Patrones visuales complejos","y que se enfoca en"),
                             ("Replicar el sistema visual humano", None)
                        ],
                        [
                            # RAMA 2: Representación de Imagen y Geometría (Nueva rama)
                            (None, "Una imagen se representa como una"),
                            ("Matriz de píxeles", "donde cada"),
                            ("Píxel", "tiene un"),
                            ("Valor de intensidad", "en imágenes en"),
                            ("Escala de grises", "o múltiples valores en"),
                            ("Modelos de color", "como"),
                            ("RGB (Rojo, Verde, Azul)", "para la"),
                            ("Visualización en pantalla", "o"),
                            ("HSV/HSL", "para separar la"),
                            ("Intensidad de la tonalidad", "el preprocesamiento incluye"),
                            ("Transformaciones geométricas", "como"),
                            ("Rotación, Escala, Traslación", "para"),
                            ("Normalizar la orientación y tamaño", "y"),
                            ("Filtrado", "para"),
                            ("Reducción de ruido o realce de bordes", "usando"),
                            ("Convoluciones", "con un"),
                            ("Kernel o filtro", "la detección de"),
                            ("Puntos de interés (Keypoints)", "como"),
                            ("SIFT o SURF", "permite encontrar"),
                            ("Características robustas", "para el"),
                            ("Emparejamiento de imágenes (Matching)", "y la"),
                            ("Calibración de cámara", "corrige las"),
                            ("Distorsiones de la lente", "y determina los"),
                            ("Parámetros intrínsecos y extrínsecos", None)
                        ]],
                    },
                    {
                        "titulo": "4.3.2. Desarrollos actuales y aplicaciones",
                        "conector": "que se enfocan en",
                        "ramas": [[
                            (None,"Los desarrollos se enfocan en"),
                             ("Visión 3D","para"),
                             ("Reconstrucción de escenas","y"),
                             ("Reconocimiento de acciones","para"),
                             ("Entender el comportamiento","y"),
                             ("Modelos generativos (GANs/VAEs)","para"),
                             ("Creación de imágenes sintéticas","con aplicaciones en"),
                             ("Control de calidad industrial","para"),
                             ("Detección de defectos","y en"),
                             ("Vigilancia inteligente","para"),
                             ("Seguimiento de personas o eventos","y"),
                             ("Vehículos autónomos","para"),
                             ("Percepción del entorno","y"),
                             ("Realidad aumentada/virtual","para"),
                             ("Interacciones inmersivas","así como en"),
                             ("Reconocimiento facial","para"),
                             ("Seguridad y autenticación","y en"),
                             ("Análisis de imágenes satelitales","para"),
                             ("Monitoreo ambiental", None)
                        ],
                        [
                            # RAMA 2: Segmentación Semántica y Modelos Generativos (Nueva rama)
                            (None, "Otros desarrollos clave son la"),
                            ("Segmentación Semántica", "que asigna una"),
                            ("Etiqueta de clase a cada píxel", "de la imagen, y la"),
                            ("Segmentación de Instancia", "que además"),
                            ("Diferencia entre objetos de la misma clase", "utilizando arquitecturas como"),
                            ("U-Net o Mask R-CNN", "también avanzan los"),
                            ("Modelos generativos", "para tareas de"),
                            ("Inpainting (completar imágenes)", "y"),
                            ("Super-resolución", "para aumentar la"),
                            ("Calidad de la imagen", "y el"),
                            ("Seguimiento de objetos (Object Tracking)", "en"),
                            ("Secuencias de video", "para aplicaciones de"),
                            ("Vigilancia o análisis de deportes", "otra área es la"),
                            ("Estimación de pose humana", "para"),
                            ("Reconocimiento de gestos o análisis de movimiento", "y la"),
                            ("Reconstrucción 3D a partir de una sola imagen (Single-view 3D)", "además del"),
                            ("Etiquetado automático de imágenes", "para la"),
                            ("Organización de grandes bases de datos visuales", "y la"),
                            ("Síntesis de imágenes a partir de texto", "con modelos como"),
                            ("DALL-E o Stable Diffusion", "y el uso en"),
                            ("Realidad Mixta", "para anclar"),
                            ("Objetos virtuales", "en el"),
                            ("Mundo real", None)
                        ]],
                    },
                ],
            },
            {
                "titulo": "4.4. Lógica difusa (Fuzzy Logic)",
                "conector": "Aplica la teoría de",
                "ramas": [
                    {
                        "titulo": "4.4.1. Conceptos básicos",
                        "conector": "que es un",
                        "ramas": [[
                            (None,"Es un"),
                             ("Sistema de lógica","que maneja el"),
                             ("Razonamiento aproximado","a diferencia de la"),
                             ("Lógica booleana","que usa solo"),
                             ("Valores verdadero (1) y falso (0)","la lógica difusa usa"),
                             ("Grados de verdad","en el intervalo"),
                             ("De 0 a 1","donde un concepto puede ser"),
                             ("Parcialmente verdadero y parcialmente falso","se basa en la"),
                             ("Teoría de conjuntos difusos","donde los elementos tienen un"),
                             ("Grado de pertenencia (membership degree)","a un conjunto, y se compone de"),
                             ("Fuzzificación","que convierte"),
                             ("Entradas nítidas (crisp)","a"),
                             ("Valores difusos","y"),
                             ("Base de reglas","con"),
                             ("Reglas IF-THEN","y"),
                             ("Inferencia","que aplica las reglas para obtener"),
                             ("Salidas difusas","y"),
                             ("Defuzzificación","que convierte las"),
                             ("Salidas difusas","a"),
                             ("Valores nítidos", None)
                        ],
                        [
                            # RAMA 2: Funciones de Pertenencia y Operadores Difusos (Nueva rama)
                            (None, "El concepto clave es la"),
                            ("Función de pertenencia (Membership Function)", "que define el"),
                            ("Grado en que un valor pertenece a un conjunto difuso", "y puede tener formas"),
                            ("Triangular, Trapezoidal o Gaussiana", "las variables del sistema se llaman"),
                            ("Variables lingüísticas", "(e.g., 'temperatura'), cuyos valores son"),
                            ("Términos lingüísticos", "las operaciones lógicas se redefinen con"),
                            ("Operadores difusos", "para la"),
                            ("Intersección (AND)", "se usa una"),
                            ("T-Norma (e.g., mínimo)", "y para la"),
                            ("Unión (OR)", "se usa una"),
                            ("S-Norma (o T-Conorma, e.g., máximo)", "el motor de inferencia puede ser de tipo"),
                            ("Mamdani", "que produce un"),
                            ("Conjunto difuso como salida", "o de tipo"),
                            ("Sugeno (o TSK)", "donde la salida es una"),
                            ("Función lineal de las entradas", "lo que es"),
                            ("Computacionalmente más eficiente", "la base de reglas es el"),
                            ("Conocimiento del experto", "capturado en"),
                            ("Formato legible", "y la defuzzificación puede usar métodos como el"),
                            ("Centroide", "para encontrar el"),
                            ("Punto de equilibrio de la forma de salida", "o la"),
                            ("Media del máximo", "para simplificar "),
                            ("el cálculo", None)
                        ]],
                    },
                    {
                        "titulo": "4.4.2. Desarrollos actuales y aplicaciones",
                        "conector": "que se enfocan en",
                        "ramas": [[
                            (None,"Los desarrollos se enfocan en"),
                             ("Sistemas híbridos","que combinan"),
                             ("Lógica difusa con redes neuronales (Neuro-Fuzzy)","para"),
                             ("Optimizar el aprendizaje","con aplicaciones en"),
                             ("Sistemas de control","para"),
                             ("Control de temperatura o velocidad","que requieren"),
                             ("Decisiones suaves","y en"),
                             ("Electrodomésticos inteligentes","para"),
                             ("Ajustar automáticamente parámetros","y en"),
                             ("Sistemas de diagnóstico médico","para"),
                             ("Manejo de síntomas inciertos","y en"),
                             ("Reconocimiento de patrones","para"),
                             ("Datos ruidosos o incompletos","además de en"),
                             ("Toma de decisiones financieras","para"),
                             ("Evaluación de riesgos ambigua","y en"),
                             ("Control de tráfico","para"),
                             ("Optimización del flujo vehicular", None)
                        ],
                        [
                            # RAMA 2: Clustering Difuso y Sistemas de Inferencia Adaptativos (Nueva rama)
                            (None, "Otros desarrollos incluyen el"),
                            ("Clustering difuso", "como el algoritmo"),
                            ("Fuzzy C-Means (FCM)", "que permite a un"),
                            ("Dato pertenecer a múltiples clusters", "con diferentes grados, y los"),
                            ("Sistemas de Inferencia Neuro-Difusos Adaptativos (ANFIS)", "que usan"),
                            ("Redes neuronales para ajustar automáticamente", "las"),
                            ("Funciones de pertenencia y reglas", "a partir de datos, con aplicaciones en"),
                            ("Procesamiento de imágenes", "para"),
                            ("Filtrado de ruido o segmentación", "y en"),
                            ("Análisis de series temporales", "para"),
                            ("Previsiones financieras o meteorológicas", "donde hay"),
                            ("Incertidumbre inherente", "también en"),
                            ("Robótica móvil", "para la"),
                            ("Navegación y evasión de obstáculos", "donde las decisiones no son binarias, y en"),
                            ("Minería de datos", "con"),
                            ("Árboles de decisión difusos", "para generar"),
                            ("Reglas interpretables", "a partir de bases de datos complejas, y en"),
                            ("Evaluación de la calidad del agua", "para modelar"),
                            ("Indicadores ambientales ambiguos", "e incluso en"),
                            ("Videojuegos", "para controlar el"),
                            ("Comportamiento de personajes no jugadores (NPCs)", "de forma "),
                            ("más humana", None)
                        ]],
                    },
                ],
            },
            {
                "titulo": "4.5. Procesamiento de Lenguaje Natural (PLN)",
                "conector": "Se centra en la",
                "ramas": [
                    {
                        "titulo": "4.5.1. Conceptos básicos",
                        "conector": "que es el",
                        "ramas": [[
                            (None,"Es el"),
                             ("Campo de la IA","que permite a las"),
                             ("Máquinas","entender, interpretar y"),
                             ("Generar lenguaje humano","e implica"),
                             ("Análisis morfológico","para"),
                             ("Estudiar la estructura de palabras","y"),
                             ("Análisis sintáctico","para"),
                             ("Estudiar la estructura de la oración","y"),
                             ("Análisis semántico","para"),
                             ("Entender el significado","y"),
                             ("Tokenización","que divide el texto en"),
                             ("Unidades más pequeñas","y"),
                             ("Modelos de lenguaje","que predicen la"),
                             ("Siguiente palabra o secuencia","y utilizan"),
                             ("Representaciones vectoriales (Embeddings)","para"),
                             ("Capturar el significado contextual","y el"),
                             ("Aprendizaje profundo (Deep Learning)","para"),
                             ("Mejorar la precisión", None)
                        ],
                        [
                            # RAMA 2: Tareas Fundamentales y Pipeline de PLN (Nueva rama)
                            (None, "El proceso sigue un"),
                            ("Pipeline de PLN", "que comienza con la"),
                            ("Recopilación de texto (Corpus)", "luego se realiza"),
                            ("Limpieza y preprocesamiento", "que incluye"),
                            ("Eliminación de stopwords", "y"),
                            ("Lematización o Stemming", "para"),
                            ("Reducir palabras a su raíz", "luego se pasa a la"),
                            ("Extracción de características", "usando técnicas como"),
                            ("Bolsa de Palabras (Bag-of-Words)", "o"),
                            ("TF-IDF", "para representar el"),
                            ("Texto numéricamente", "tareas comunes incluyen"),
                            ("Etiquetado de Parte de la Oración (POS Tagging)", "para asignar"),
                            ("Roles gramaticales (verbo, sustantivo)", "y el"),
                            ("Reconocimiento de Entidades Nombradas (NER)", "para identificar"),
                            ("Personas, lugares, organizaciones", "y el"),
                            ("Análisis de dependencias", "para entender las"),
                            ("Relaciones gramaticales", "otro concepto es el de"),
                            ("N-gramas", "para capturar"),
                            ("Secuencias de palabras", "y los"),
                            ("Word Embeddings (e.g., Word2Vec, GloVe)", "que aprenden"),
                            ("Representaciones vectoriales densas", "capturando"),
                            ("Relaciones semánticas", "entre "),
                            ("palabras", None)
                        ]],
                    },
                    {
                        "titulo": "4.5.2. Desarrollos actuales y aplicaciones",
                        "conector": "que incluyen",
                        "ramas": [[
                            (None,"Los desarrollos incluyen"),
                             ("Modelos basados en Transformers (e.g., GPT, BERT)","que logran"),
                             ("Resultados de vanguardia","en tareas como"),
                             ("Traducción automática avanzada","y"),
                             ("Generación de texto coherente","con aplicaciones en"),
                             ("Chatbots y asistentes virtuales","para"),
                             ("Interacción conversacional","y en"),
                             ("Análisis de sentimiento","para"),
                             ("Clasificar opiniones en texto","y"),
                             ("Resumen automático de texto","para"),
                             ("Extraer ideas principales","así como en"),
                             ("Sistemas de respuesta a preguntas (QA)","para"),
                             ("Recuperar información específica","y en"),
                             ("Detección de spam y fraude","para"),
                             ("Seguridad digital", None)
                        ],
                        [
                            # RAMA 2: Modelos Contextuales y Aplicaciones de Nicho (Nueva rama)
                            (None, "Otros desarrollos se centran en"),
                            ("Modelos de lenguaje contextuales (e.g., ELMo, BERT)", "que generan"),
                            ("Representaciones de palabras", "dependiendo de la"),
                            ("Oración completa", "lo que mejora la"),
                            ("Comprensión del contexto", "y en"),
                            ("PLN Zero-shot y Few-shot", "donde los modelos realizan"),
                            ("Tareas para las que no fueron explícitamente entrenados", "además de"),
                            ("Modelado de tópicos (Topic Modeling)", "para descubrir"),
                            ("Temas latentes en grandes colecciones de texto", "con aplicaciones en"),
                            ("Análisis de argumentos (Argument Mining)", "para extraer"),
                            ("Estructuras de argumentación", "y en"),
                            ("Detección de noticias falsas (Fake News)", "y"),
                            ("Análisis de toxicidad en línea", "y en"),
                            ("PLN para el cuidado de la salud", "para extraer"),
                            ("Información de registros médicos electrónicos", "así como en"),
                            ("Generación de código a partir de texto", "con modelos como"),
                            ("Copilot", "y en la"),
                            ("Simplificación automática de texto", "para mejorar la"),
                            ("Accesibilidad", "e incluso en"),
                            ("Lingüística computacional forense", "para"),
                            ("Análisis de autoría de textos", "y en la"),
                            ("Interfaz cerebro-computadora", "para"),
                            ("Decodificar pensamientos a texto", None)
                        ]],
                    },
                ],
            },
            {
                "titulo": "4.6. Sistemas Expertos (SE)",
                "conector": "Son parte de los",
                "ramas": [
                    {
                        "titulo": "4.6.1. Conceptos básicos",
                        "conector": "que son un",
                        "ramas": [[
                            (None,"Son un"),
                             ("Programa de computadora","diseñado para"),
                             ("Emular la capacidad de toma de decisiones","de un"),
                             ("Experto humano","en un"),
                             ("Dominio limitado","y se componen de"),
                             ("Base de conocimientos","que almacena"),
                             ("Hechos y reglas (heurísticas)","y"),
                             ("Motor de inferencia","que aplica las reglas para"),
                             ("Derivar conclusiones","y"),
                             ("Interfaz de usuario","para"),
                             ("Interacción con el usuario","además de un"),
                             ("Módulo de adquisición de conocimiento","para"),
                             ("Cargar nuevas reglas","y un"),
                             ("Módulo de explicación","para"),
                             ("Justificar las conclusiones","y el"),
                             ("Conocimiento","se representa a menudo como"),
                             ("Reglas de producción (IF-THEN)", None)
                        ],
                        [
                            # RAMA 2: Representación del Conocimiento e Inferencia (Nueva rama)
                            (None, "El conocimiento se puede representar con"),
                            ("Marcos (Frames)", "que son estructuras de datos"),
                            ("Similares a objetos", "con"),
                            ("Ranuras (Slots) y facetas (Facets)", "o mediante"),
                            ("Redes semánticas", "que usan"),
                            ("Nodos para conceptos y arcos para relaciones", "y también con"),
                            ("Lógica de predicados", "para una"),
                            ("Representación formal y poderosa", "el motor de inferencia utiliza"),
                            ("Estrategias de resolución de conflictos", "cuando"),
                            ("Múltiples reglas pueden aplicarse", "como"),
                            ("Especificidad", "(la regla más específica gana) o"),
                            ("Recencia",  "el proceso de inferencia maneja la"),
                            ("Incertidumbre", "mediante"),
                            ("Factores de certeza", "que son valores numéricos que indican la"),
                            ("Confianza en una conclusión", "el conocimiento en la base debe ser"),
                            ("Preciso y relevante", "y es adquirido del"),
                            ("Experto de dominio", "a través de un"),
                            ("Ingeniero de conocimiento", "quien"),
                            ("Formaliza y estructura la información", "para que el"),
                            ("Sistema pueda ", "utilizarla"),
                            ("efectivamente", None)
                        ]],
                    },
                    {
                        "titulo": "4.6.2. Clasificación",
                        "conector": "que se clasifican por",
                        "ramas": [[
                            (None,"Se clasifican por"),
                             ("Función","en"),
                             ("Diagnóstico","para"),
                             ("Identificar problemas (e.g., enfermedades)","y"),
                             ("Prescripción","para"),
                             ("Recomendar acciones","o"),
                             ("Control","para"),
                             ("Monitorear sistemas","y"),
                             ("Diseño","para"),
                             ("Crear configuraciones","también por"),
                             ("Estrategia de inferencia","en"),
                             ("Encadenamiento hacia adelante (Forward Chaining)","que va de"),
                             ("Datos a conclusiones","y"),
                             ("Encadenamiento hacia atrás (Backward Chaining)","que va de"),
                             ("Objetivos a datos requeridos","y por"),
                             ("Dominio","en"),
                             ("Sistemas de dominio específico","o"),
                             ("Sistemas generales", None)
                        ],
                        [
                            # RAMA 2: Arquitectura y Manejo del Conocimiento (Nueva rama)
                            (None, "Se clasifican también por su"),
                            ("Arquitectura", "en"),
                            ("Sistemas basados en reglas", "que son los"),
                            ("Más comunes y directos", "y"),
                            ("Sistemas basados en casos (CBR)", "que resuelven problemas"),
                            ("Recordando y adaptando soluciones pasadas", "y"),
                            ("Sistemas basados en modelos", "que tienen una"),
                            ("Simulación profunda del dominio", "permitiendo"),
                            ("Razonamiento desde primeros principios", "además, por cómo manejan el conocimiento, en"),
                            ("Sistemas estáticos", "cuya base de conocimientos"),
                            ("No cambia durante la ejecución", "y"),
                            ("Sistemas dinámicos", "que pueden"),
                            ("Aprender y actualizar su conocimiento", "a través de la interacción, y por su"),
                            ("Dependencia del tiempo", "en"),
                            ("Sistemas de tiempo real", "que deben"),
                            ("Responder dentro de plazos estrictos", "y"),
                            ("Sistemas de tiempo no real", "donde la velocidad"),
                            ("No es el factor más crítico", "y por el tipo de interfaz en"),
                            ("Sistemas de consulta", "o"),
                            ("Sistemas de tutoría inteligente", "diseñados para"),
                            ("Enseñanza y formación", None)
                        ]],
                    },
                    {
                        "titulo": "4.6.3. Desarrollos actuales y aplicaciones",
                        "conector": "que se enfocan en",
                        "ramas": [[
                            (None,"Los desarrollos se enfocan en"),
                             ("Integración con Machine Learning","para"),
                             ("Aprender reglas automáticamente","y"),
                             ("Sistemas basados en web","para"),
                             ("Acceso remoto","con aplicaciones en"),
                             ("Diagnóstico médico (e.g., MYCIN)","para"),
                             ("Asistir a doctores","y en"),
                             ("Configuración de sistemas informáticos","para"),
                             ("Garantizar la compatibilidad","y"),
                             ("Planificación logística","para"),
                             ("Optimizar rutas y recursos","así como en"),
                             ("Análisis de fallas en ingeniería","para"),
                             ("Identificar la causa raíz","y en"),
                             ("Sistemas de recomendación avanzados","para"),
                             ("Decisiones expertas basadas en preferencias", None)
                        ],
                        [
                            # RAMA 2: Hibridación y Dominios Modernos (Nueva rama)
                            (None, "Las aplicaciones modernas incluyen la"),
                            ("Hibridación con otras técnicas de IA", "como"),
                            ("Algoritmos genéticos", "para"),
                            ("Optimizar la base de reglas", "o su integración en"),
                            ("Agentes inteligentes", "para dotarlos de"),
                            ("Capacidad de razonamiento experto", "se aplican en"),
                            ("Ciberseguridad", "para la"),
                            ("Detección de intrusiones y análisis de malware", "y en la"),
                            ("Gestión de la cadena de suministro", "para"),
                            ("Optimizar la logística y el inventario", "también en"),
                            ("Derecho y cumplimiento normativo (LegalTech)", "para"),
                            ("Revisión de contratos o asistencia en litigios", "y en la"),
                            ("Composición musical o artística", "para generar obras que sigan"),
                            ("Ciertos estilos o reglas teóricas", "así como en"),
                            ("Juegos", "para la"),
                            ("Toma de decisiones estratégicas de NPCs", "y en la"),
                            ("Ingeniería de software", "para la"),
                            ("Depuración de código o recomendación de refactorización", "además, los"),
                            ("Sistemas de explicación (XAI)", "son una evolución para"),
                            ("Hacer transparentes las decisiones de modelos complejos", "como las "),
                            ("redes neuronales",  None)
                        ]],
                    },
                ],
            },
        ],
    }
]

if NORMALIZAR_TUPLAS:
    try:
        from utilidades.ajuste_mapa_conceptual import normalizar_concept_map

        concept_map = normalizar_concept_map(
            concept_map, palabras_por_slot=PALABRAS_POR_POSICION
        )
    except Exception as exc:  # pragma: no cover - solo para ayuda en runtime
        print(f"No se pudo normalizar concept_map: {exc}", file=sys.stderr)

CONFIG = {
    "FONT_FAMILY": "Courier New",
    "FONT_SIZE": 12,
    "FONT_COLOR": "#1f2937",
    "STROKE_W": 1.2,
    "EDGE_COLOR": "#38579b",
    "BOX_ARC_SIZE": 30,
    "BOX_SHADOW": True,
    "MAIN_FILL_COLOR": "#dbeafe",
    "MAIN_STROKE_COLOR": "#1d4ed8",
    "SUBTITLE_FILL_COLOR": "#e2e8f0",
    "SUBTITLE_STROKE_COLOR": "#475569",
    "CONNECTOR_FONT_FAMILY": "Verdana",
    "CONNECTOR_FONT_SIZE": 9,
    "CONNECTOR_FONT_COLOR": "#111827",
    "CONNECTOR_BG_COLOR": "#f8fafc",
    "CONNECTOR_BORDER_COLOR": "#cbd5e1",
    "CONNECTOR_SHADOW": False,
    "CONNECTOR_TEXT_SHADOW": True,
    "BOX_W": 100,
    "BOX_H": 70,
    "X_STEP": 150,
    "Y_STEP": 110,
    "MAIN_TO_SUBTITLE": 130,
    "SUBTITLE_TO_BRANCH": 150,
    "SUBTITLE_GAP": 80,
    "GROUP_GAP": 200,
    "PALETTE": [
        ("#fff3c4", "#d97706"),
        ("#d8ffe5", "#15803d"),
        ("#e0eeff", "#1d4ed8"),
        ("#ffead2", "#c2410c"),
    ],
    "START_X": 120,
    "START_Y": 40,
    "OUTPUT_FILE": os.path.join("Mapas", "Mapa_conceptual_IA_Juan.drawio"),
}


def run():
    """Permite ejecutar el generador directamente desde este archivo."""
    base_dir = os.path.dirname(__file__)
    scripts_dir = os.path.join(base_dir, "Scripts")
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)

    from Mapas_conceptuales import generar_mapa_conceptual

    out_path = generar_mapa_conceptual(concept_map, CONFIG)
    print(f"Mapa conceptual generado en: {out_path}")


if __name__ == "__main__":
    run()
